/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunnybear_library_view_image_util_StackNative */

#ifndef _Included_com_sunnybear_library_view_image_util_StackNative
#define _Included_com_sunnybear_library_view_image_util_StackNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunnybear_library_view_image_util_StackNative
 * Method:    blurBitmap
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_sunnybear_library_view_image_util_StackNative_blurBitmap
        (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_sunnybear_library_view_image_util_StackNative
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_sunnybear_library_view_image_util_StackNative_blurPixels
        (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
