//
// Created by sunnybear on 16/1/26.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_genius_blur_StackNative */


#ifndef SAMPLE_COM_SUNNYBEAR_LIBRARY_VIEW_IMAGE_UTIL_STACKNATIVE_H
#define SAMPLE_COM_SUNNYBEAR_LIBRARY_VIEW_IMAGE_UTIL_STACKNATIVE_H

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunnybear_library_view_image_util_StackNative
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL
        Java_com_sunnybear_library_view_image_util_StackNative_blurPixels
        (JNIEnv
         *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_sunnybear_library_view_image_util_StackNative
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL
        Java_com_sunnybear_library_view_image_util_StackNative_blurBitmap
        (JNIEnv
         *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif

